### ISSUE TITLE
execjs._exceptions.ProgramError: ReferenceError: Can't find variable: exports   执行js会有报错

### ISSUE THREAD

**Issue by rhypowang** [zkqiang/Zhihu-Login#12]

**Comment by zkqiang** [comment]
没装Node.js，或者装了但没被execjs正确引用

**Comment by framinghu** [comment]
I met this issue too recent, please make sure the node version should be larger than 5.11, detail please refer to below link:
https://stackoverflow.com/questions/14573001/nodejs-how-to-decode-base64-encoded-string-back-to-binary

**Comment by rhypowang** [comment]
ok thank you very much------------------ 原始邮件 ------------------
发件人: "framinghu"<notifications@github.com>
发送时间: 2019年10月29日(星期二) 下午3:49
收件人: "zkqiang/zhihu-login"<zhihu-login@noreply.github.com>;
抄送: "hbaianni"<1079395071@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [zkqiang/zhihu-login] execjs._exceptions.ProgramError: ReferenceError: Can't find variable: exports   执行js会有报错 (#12)



I met this issue too recent, please make sure the node version should be larger than 5.11, detail please refer to below link:
 https://stackoverflow.com/questions/14573001/nodejs-how-to-decode-base64-encoded-string-back-to-binary
 
&mdash;
