### ISSUE TITLE
浏览器拦截sign_in请求的问题

### ISSUE THREAD

**Issue by makoto4423** [zkqiang/Zhihu-Login#14]
这里用谷歌浏览器，登录知乎的时候，sign_in这个请求在console那里一闪而过（疑似被知乎清掉），请问这个问题要怎么解决？

**Comment by zkqiang** [comment]
不是清掉... 是页面跳转导致

console 勾选 `preserve log` 即可

**Comment by makoto4423** [comment]
> 不是清掉... 是页面跳转导致
> 
> console 勾选 `preserve log` 即可

好的，谢谢。
