### ISSUE TITLE
如何分析Headers中的必要的POST字段？

### ISSUE THREAD

**Issue by zoeysnowy** [zkqiang/Zhihu-Login#2]
谢谢NN的分享！想请教下如何测试出Headers里面的必要POST字段的（Authorization，x-xsrftoken）？比如content-type, content-length, origin这样的字段是一个个添加/去除post过去尝试的吗？然后好像也没有看到Headers中有Authorization这个字段？

另外对于”倒立的文字“看到一个更好的解法是录入7个汉字的坐标（其实是固定的），只要input汉字的序号就可以返回坐标值了。

最后还有个神奇的问题是，我在mac上用Charles似乎无法从static.zhihu.com上顺利抓取js，返回的结果一直是404；SSL proxy certificate已设置，其他网站好像没这个问题；最后是通过Safari的resources找到的js文件。不知道这个情况LZ是否有insights~十分感谢啦~！

**Comment by zkqiang** [comment]
Authorization字段：我刚刚测试，发现登录的POST已经去掉了这个字段，所以现在加不加都可以

增删字段的问题：如果你想简化字段，可以先从几个主要字段开始，如Accept  User-Agent  Referer 及 一些签名字段，请求失败再加入更多的字段，一般就很快可以测试出可用的；当然懒的话就直接用原始所有字段好了

汉字倒立：经过测试汉字X坐标还是有偏差，固定坐标偶尔还是会出界，不过可以尝试像素识别来确定坐标 （其实我用PLT纯属好玩...本身可以控制只用英文验证码）

JS抓取的问题：最好用浏览器工具，因为是原始请求，用Charles我有空试下
