### ISSUE TITLE
windows 下无法点击倒立的汉字

### ISSUE THREAD

**Issue by ilpanda** [zkqiang/Zhihu-Login#7]
### windows 下无法点击倒立的汉字
系统 : windows
IDE  :  Pycharm

1.鼠标点击无效的解决方案 
https://blog.csdn.net/winner_looser/article/details/88013878

2.点击汉字  , 无法回车提交 , 知乎仍然无法识别 , 如下图 : 
![](https://pic.superbed.cn/item/5c7e458a3a213b0417460f62)
```
points = plt.ginput(7)
```
改为
```
points = plt.ginput(1) 
```
登录成功

**Comment by zkqiang** [comment]
感谢，已更新到代码注释里
